// Generated by CoffeeScript 1.3.3
(function() {
  var CarouselController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  CarouselController = (function() {

    function CarouselController() {
      this.goToNext = __bind(this.goToNext, this);

      this.goToItem = __bind(this.goToItem, this);

      this.render = __bind(this.render, this);

      this.controls = __bind(this.controls, this);

      this.template = __bind(this.template, this);

      var _this = this;
      this.el = $('.carousel');
      this.item = 0;
      this.el.addClass(this.item);
      this.forward = true;
      this.count = -1;
      this.countArray = ['first', 'second', 'third', 'fourth'];
      window.App.WordpressFeed.on('feed-loaded:events', function(feed) {
        _this.feed = feed;
        return _this.render();
      });
      window.App.WordpressFeed.fetch(4, 'events');
    }

    CarouselController.prototype.template = function(feedItem) {
      this.count += 1;
      return "<div class=\"carousel-item " + this.countArray[this.count] + "\">\n  <img src=\"" + feedItem.image + "\" alt=\"" + feedItem.description + "\" />\n  <div class=\"carousel-details\">\n    <h2 class=\"carousel-title\">" + feedItem.title + "</h2>\n    <p class=\"carousel-description\">" + feedItem.description + "</p>\n    <a href=\"" + feedItem.url + " class=\"carousel-link\">" + feedItem.linkText + "</a>\n  </div>\n</div>";
    };

    CarouselController.prototype.controls = function() {
      var num, radios, _i;
      radios = new String;
      for (num = _i = 0; _i <= 3; num = ++_i) {
        radios = radios + ("<input type=\"radio\" name=\"carousel\" value=\"" + num + "\">");
      }
      return '<div class="carousel-controls">' + radios + "</div>";
    };

    CarouselController.prototype.render = function() {
      var item, _i, _len, _ref;
      _ref = this.feed;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        this.el.append(this.template(item));
      }
      this.el.append(this.controls());
      this.el.find("input[value=\"" + this.item + "\"]").prop('checked', true);
      this.el.find('input[name="carousel"]').on('click', this.goToItem);
      return this.timerId = setInterval(this.goToNext, 10000);
    };

    CarouselController.prototype.goToItem = function(e) {
      clearInterval(this.timerId);
      this.el.removeClass(this.countArray[this.item]);
      this.item = e.currentTarget.value;
      return this.el.addClass(this.countArray[this.item]);
    };

    CarouselController.prototype.goToNext = function() {
      this.el.removeClass(this.countArray[this.item]);
      if (this.forward) {
        if (this.item < 3) {
          this.item += 1;
        } else {
          this.forward = false;
          this.item -= 1;
        }
      } else {
        if (this.item > 0) {
          this.item -= 1;
        } else {
          this.forward = true;
          this.item += 1;
        }
      }
      this.el.find("input[value=\"" + this.item + "\"]").prop('checked', true);
      return this.el.addClass(this.countArray[this.item]);
    };

    return CarouselController;

  })();

  window.App.CarouselController = CarouselController;

}).call(this);
