// Generated by CoffeeScript 1.3.3
(function() {
  var Events,
    __slice = [].slice;

  Events = (function() {

    function Events() {}

    Events.prototype.trigger = function() {
      var args, event;
      event = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return this.constructor.trigger(event, args);
    };

    Events.trigger = function() {
      var args, event;
      event = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return $(document).trigger(event, args);
    };

    Events.prototype.on = function(event, callback) {
      return this.constructor.trigger(event(callback));
    };

    Events.on = function(event, callback) {
      return $(document).on(event, function(event, args) {
        return callback(args);
      });
    };

    return Events;

  })();

  window.App.Events = Events;

}).call(this);
