// Generated by CoffeeScript 1.3.3
(function() {
  var Map;

  Map = (function() {

    function Map(opts) {
      this.el = opts.element;
      opts.lat || (opts.lat = 1.37);
      opts.lng || (opts.lng = 32.29);
      this.defaultZoom = opts.zoom || 13;
      this.styleUrl = opts.styleUrl || "http://{s}.tile.cloudmade.com/703a104d15d44e2885f6cedeaaec6d30/78177/256/{z}/{x}/{y}.png";
      this.center = new L.LatLng(opts.lat, opts.lng);
      this.setupMap();
    }

    Map.prototype.setupMap = function() {
      if ($("#" + this.el).length > 0) {
        this.map = L.map(this.el, {
          zoom: 13
        });
        this.map.setView(this.center, this.defaultZoom);
        this.mainTileLayer = L.tileLayer(this.styleUrl);
        return this.mainTileLayer.addTo(this.map);
      } else {
        return console.log("could not find a map div");
      }
    };

    return Map;

  })();

  window.App.Map = Map;

}).call(this);
