// Generated by CoffeeScript 1.3.3
(function() {
  var MarkFudge;

  MarkFudge = (function() {

    function MarkFudge() {}

    MarkFudge.fudge = function() {
      var _this = this;
      return $(".markdownSection").each(function(index, d) {
        var html;
        html = _this.generateHTML($(d).html().replace(/^\s+/, ''));
        $(d).html(html);
        return $(d).show();
      });
    };

    MarkFudge.generateHTML = function(mark) {
      return marked(mark);
    };

    return MarkFudge;

  })();

  window.App.MarkFudge = MarkFudge;

}).call(this);
