// Generated by CoffeeScript 1.3.3
(function() {
  var Model,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  Model = (function() {

    function Model() {
      this.fromJSON = __bind(this.fromJSON, this);

      this.fetch = __bind(this.fetch, this);

    }

    Model.prototype.constrcutor = function(opts) {
      return this.id = opts.id;
    };

    Model.prototype.base_url = 'url_here';

    Model.prototype.trigger = function() {
      var args, event;
      event = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return $(document).trigger(event, args);
    };

    Model.prototype.on = function(event, callback) {
      return $(document).on(event, callback);
    };

    Model.prototype.fetch = function() {
      return $.getJSON("http://" + this.base_url + "/" + this.url + "/" + this.id + ".json", function(data) {
        this.fromJSON(data);
        return this.trigger('fetch', this);
      });
    };

    Model.prototype.fromJSON = function(data) {
      var key, value, _i, _len, _results;
      _results = [];
      for (value = _i = 0, _len = data.length; _i < _len; value = ++_i) {
        key = data[value];
        _results.push(this[key] = value);
      }
      return _results;
    };

    return Model;

  })();

  window.App.Model = Model;

}).call(this);
