// Generated by CoffeeScript 1.3.3
(function() {
  var Model;

  Model = (function() {

    function Model() {}

    Model.prototype.constrcutor = function(opts) {
      return this.id = opts.id;
    };

    Model.prototype.base_url = 'url_here';

    Model.prototype.fetch = $.getJSON("http://" + Model.base_url + "/" + Model.url + "/" + Model.id + ".json", function(data) {
      var key, value, _i, _len, _results;
      _results = [];
      for (value = _i = 0, _len = data.length; _i < _len; value = ++_i) {
        key = data[value];
        _results.push(this[key] = value);
      }
      return _results;
    });

    return Model;

  })();

  window.App.Model = Model;

}).call(this);
