// Generated by CoffeeScript 1.3.3
(function() {
  var PeopleController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  PeopleController = (function(_super) {

    __extends(PeopleController, _super);

    function PeopleController(personType) {
      this.personType = personType;
      this.renderAll = __bind(this.renderAll, this);

      PeopleController.__super__.constructor.call(this, "." + this.personType, window.App.Person);
    }

    PeopleController.prototype.renderAll = function() {
      var key, model, roles, _ref, _ref1;
      roles = this.personType === 'board' ? ['board_member'] : ['team', 'director', 'intern'];
      _ref = this.models;
      for (key in _ref) {
        model = _ref[key];
        if (_ref1 = model.role, __indexOf.call(roles, _ref1) >= 0) {
          this.el.append(this.listTemplate(model));
        }
      }
      return this.startList();
    };

    PeopleController.prototype.listTemplate = function(model) {
      return "<section class=\"board normal\">\n  <img src=\"" + model.image + " || '//placehold.it/235x160.png'}\" width=\"235\" height=\"160\" />\n  <div class=\"popup\">\n    <span class=\"name\">" + model.name + "</span>\n    <span class=\"email\">" + model.email + "</span>\n    <span class=\"bio\">" + model.bio + "</span>\n  </div>\n</section>";
    };

    return PeopleController;

  })(window.App.Controller);

  window.App.PeopleController = PeopleController;

}).call(this);
