// Generated by CoffeeScript 1.3.3
(function() {
  var Person,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Person = (function(_super) {

    __extends(Person, _super);

    function Person(opts) {
      Person.__super__.constructor.call(this, opts);
    }

    Person.url = 'people';

    return Person;

  })(window.App.Model);

  window.App.Person = Person;

}).call(this);
