// Generated by CoffeeScript 1.3.3
(function() {
  var PowerfulController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  PowerfulController = (function() {

    function PowerfulController() {
      this.render = __bind(this.render, this);

      this.template = __bind(this.template, this);

      var _this = this;
      this.el = $('#powerful');
      window.App.WordpressFeed.on('feed-loaded:powerful', function(feed) {
        _this.feed = feed;
        return _this.render();
      });
      window.App.WordpressFeed.fetch(10, 'powerful');
      console.log('feed');
    }

    PowerfulController.prototype.template = function(feedItem) {
      return "<div class=\"two columns\">\n  <div class=\"narrow column\">\n    <figure>\n      <img src=\"" + feedItem.image + "\" />\n    </figure>\n  </div>\n  \n<div class=\"wide column\">\n  <h4>" + feedItem.title + "</h4>\n  <p>" + feedItem.description + " <a href=\"" + feedItem.url + "\">" + feedItem.linkText + "</a></p>\n</div>";
    };

    PowerfulController.prototype.render = function() {
      var item, _i, _len, _ref, _results;
      _ref = this.feed;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _results.push(this.el.append(this.template(item)));
      }
      return _results;
    };

    return PowerfulController;

  })();

  window.App.PowerfulController = PowerfulController;

}).call(this);
