// Generated by CoffeeScript 1.3.3
(function() {
  var PowerfulController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  PowerfulController = (function() {

    function PowerfulController() {
      this.template = __bind(this.template, this);

      var _this = this;
      this.el = $('.powerful');
      window.App.WordpressFeed.on('feed-loaded:powerful', function(feed) {
        _this.feed = feed;
        return _this.render();
      });
      window.App.WordpressFeed.fetch(10, 'powerful');
    }

    PowerfulController.prototype.template = function(feedItem) {
      this.count += 1;
      return "<div class=\"two columns\">\n  <div class=\"narrow column\">\n    <figure>\n      <img src=\"" + feedItem.image + "\" />\n    </figure>\n  </div>\n<div class=\"wide column\">";
    };

    return PowerfulController;

  })();

  window.App.PowerfulController = PowerfulController;

}).call(this);
