// Generated by CoffeeScript 1.3.3
(function() {
  var Project;

  Project = (function() {

    function Project(opts) {
      var key, value, _i, _len;
      for (value = _i = 0, _len = opts.length; _i < _len; value = ++_i) {
        key = opts[value];
        this[key] = value;
      }
    }

    return Project;

  })();

  window.App.Project = Project;

}).call(this);
