// Generated by CoffeeScript 1.3.3
(function() {
  var SchoolController, template,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  template = function(school) {
    return "";
  };

  SchoolController = (function(_super) {

    __extends(SchoolController, _super);

    function SchoolController() {
      this.start = __bind(this.start, this);

      this.startList = __bind(this.startList, this);

      this.renderAll = __bind(this.renderAll, this);
      SchoolController.__super__.constructor.call(this, '.schools', window.App.School);
    }

    SchoolController.prototype.renderAll = function() {
      var compiled, header, key, model;
      compiled = (function() {
        var _ref, _results;
        _ref = this.models;
        _results = [];
        for (key in _ref) {
          model = _ref[key];
          _results.push(this.listTemplate(model));
        }
        return _results;
      }).call(this);
      this.el.html(compiled.join(" "));
      header = "<section class=\"normal\">\n  <h1><strong>Uganda</strong></h1>\n</section>";
      this.el.prepend(header);
      return this.startList(this.models);
    };

    SchoolController.prototype.donationsTemplate = function(model) {
      var donationType, result, _i, _len, _ref;
      result = "";
      _ref = model.donations;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        donationType = _ref[_i];
        result = result + ("<p class='donationType'> <img src='images/donationTypeImages/" + (App.School.imageForDonationType(donationType)) + ".png'></img> <br />" + donationType + " </p>");
      }
      return result;
    };

    SchoolController.prototype.listTemplate = function(model) {
      var progress, progress_text;
      progress = 'begin';
      progress_text = '';
      if (model.phase_1_complete) {
        progress = 'one-third';
        progress_text = 'Phase 1: Complete';
      }
      if (model.phase_2_complete) {
        progress = 'two-thirds';
        progress_text = 'Phase 2: Complete';
      }
      if (model.phase_3_complete) {
        progress = 'complete';
        progress_text = 'Phase 3: Complete';
      }
      return "<section class=\"school normal\">\n  <div class=\"image\">\n    <figure>\n      <div class=\"progress " + progress + "\"></div>\n      <img src=\"" + (model.image_url || '//placehold.it/128.png') + "\" />\n    </figure>\n    <figcaption>" + progress_text + "</figcaption>\n  </div>\n\n  <div class=\"content\">\n    <header>\n      <div class=\"name\">" + model.name + "</div class=\"name\">\n      <div class=\"location\">Kampala, Uganda</div>\n    </header>\n    <p>" + model.story + "</p>\n\n    <div class='storyButtons'>\n        <p><a href=\"#/" + model.slug + "\" class=\"standard-button green\">View site</a></p>\n        <p class='social'><a style='color:black' target='_blank' href=\"" + (App.SocialNetworks.twitterHref(model.name, window.location + '#' + model.slug)) + "\"><i class='icon-twitter'> </i></a></p>\n        <p class='social'><a style='color:black' target='_blank' href=\"" + (App.SocialNetworks.twitterHref(model.name, model.slug)) + "\"><i class='icon-facebook-squared'> </i></a></p>\n    </div>  \n  </div>\n</section>";
    };

    SchoolController.prototype.itemTemplate = function(model) {
      var progress, progress_text;
      $('.project-list.universities').hide();
      progress = 'begin';
      progress_text = '';
      if (model.phase_1_complete) {
        progress = 'one-third';
        progress_text = 'Phase 1: Complete';
      }
      if (model.phase_2_complete) {
        progress = 'two-thirds';
        progress_text = 'Phase 2: Complete';
      }
      if (model.phase_3_complete) {
        progress = 'complete';
        progress_text = 'Phase 3: Complete';
      }
      return "<section class=\"school normal\">\n  <div class=\"image\">\n    <figure>\n      <div class=\"progress " + progress + "\"></div>\n      <img src=\"" + (model.image_url || '//placehold.it/128.png') + "\">\n    </figure>\n  </div>\n\n  <div class=\"content\">\n    <header>\n      <div class=\"name\">" + model.name + "</div class=\"name\">\n      <div class=\"location\">Kampala, Uganda</div>\n    </header>\n    <p>" + model.story + "</p>\n    <div class='requiredDonations'>\n      <p class='schoolClassStats'>Teachers: " + (model["Teachers"] || 'unknown') + " Students: " + (model["Students"] || 'unknown') + " </p>\n      <p style='font-size:15px'>Donations Required</p>\n      " + (this.donationsTemplate(model)) + "\n      <div class=\"column\"><p><a href=\"donateGift\" class=\"orange standard-button\">Give a gift</a></p></div>\n\n    </div>\n     <div class='storyButtons'>\n        <p class='social'><a target='_blank' href=\"" + (App.SocialNetworks.twitterHref(model.name, window.location)) + "\"><i class='icon-twitter'> </i></a></p>\n        <p class='social'><a target='_blank' href=\"" + (App.SocialNetworks.twitterHref(model.name, model.slug)) + "\"><i class='icon-facebook-squared'> </i></a></p>\n    </div>  \n  </div>\n</section>\n\n<section class=\"normal\">\n  <h1><strong>Project Timeline</strong></h1>\n  <div id=\"school_timeline\"></div>\n</section>";
    };

    SchoolController.prototype.startList = function(schools) {
      var hash, schoolForMap, _ref, _results;
      if (!this.map) {
        this.map = new window.App.Map({
          element: 'map'
        });
      }
      _ref = this.models;
      _results = [];
      for (hash in _ref) {
        schoolForMap = _ref[hash];
        _results.push(this.map.addSchool(schoolForMap));
      }
      return _results;
    };

    SchoolController.prototype.start = function(school) {
      var hash, schoolForMap, _ref;
      if (!this.map) {
        this.map = new window.App.Map({
          element: 'map',
          lat: school.lat,
          lng: school.lng
        });
      }
      _ref = this.models;
      for (hash in _ref) {
        schoolForMap = _ref[hash];
        this.map.addSchool(schoolForMap);
      }
      this.map.centerSchool(school);
      if (this.currentTimeLine) {
        this.currentTimeLine.remove();
        delete this.currentTimeLine;
      }
      return this.currentTimeLine = new window.App.Timeline(school, "#school_timeline");
    };

    return SchoolController;

  })(window.App.Controller);

  window.App.SchoolController = SchoolController;

}).call(this);
