// Generated by CoffeeScript 1.3.3
(function() {
  var School,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  School = (function(_super) {

    __extends(School, _super);

    function School(opts) {
      this.fromJSON = __bind(this.fromJSON, this);
      School.__super__.constructor.call(this, opts);
      this.projects = new Array;
    }

    School.prototype.url = 'path to resource here';

    School.prototype.fromJSON = function(data) {
      var key, project, value, _i, _j, _len, _len1, _ref, _results;
      for (value = _i = 0, _len = data.length; _i < _len; value = ++_i) {
        key = data[value];
        if (key !== 'projects') {
          this[key] = value;
        }
      }
      _ref = data['projects'];
      _results = [];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        project = _ref[_j];
        _results.push(this.projects.push(new window.App.Project(project)));
      }
      return _results;
    };

    return School;

  })(window.App.Model);

  window.App.School = School;

}).call(this);
