// Generated by CoffeeScript 1.3.3
(function() {
  var School,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  School = (function(_super) {

    __extends(School, _super);

    function School(opts) {
      School.__super__.constructor.call(this, opts);
    }

    return School;

  })(window.App.Model);

  window.App.School = School;

}).call(this);
