// Generated by CoffeeScript 1.3.3
(function() {
  var School,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  School = (function(_super) {

    __extends(School, _super);

    function School(opts) {
      this.fromJSON = __bind(this.fromJSON, this);
      School.__super__.constructor.call(this, opts);
    }

    School.url = 'schools';

    School.prototype.fromJSON = function(data) {
      var key, value, _results;
      _results = [];
      for (key in data) {
        value = data[key];
        if (key !== 'projects') {
          _results.push(this[key] = value);
        }
      }
      return _results;
    };

    return School;

  })(window.App.Model);

  window.App.School = School;

}).call(this);
