// Generated by CoffeeScript 1.3.3
(function() {
  var SocialNetworks;

  SocialNetworks = (function() {

    function SocialNetworks() {}

    SocialNetworks.facebookHref = function() {
      var image, summary, title;
      title = 'Snapshot Serengeti';
      summary = 'I just classified this image on Snapshot Serengeti!';
      image = $("<a href='" + this.location.standard[0] + "'></a>").get(0).href;
      return "https://www.facebook.com/sharer/sharer.php\n?s=100\n&p[url]=" + (this.talkHref()) + "\n&p[title]=" + (encodeURIComponent(title)) + "\n&p[summary]=" + (encodeURIComponent(summary)) + "\n&p[images][0]=" + image;
    };

    SocialNetworks.twitterHref = function(orgName, url) {
      var message;
      message = "Check out the great work that Pangea Education is doing with " + orgName + " " + url + " #PangeaEducation";
      return "http://twitter.com/home?status=" + (encodeURIComponent(message));
    };

    SocialNetworks.pinterestHref = function() {
      return "http://pinterest.com/pin/create/button/?url=" + (this.talkHref());
    };

    return SocialNetworks;

  })();

  window.App.SocialNetworks = SocialNetworks;

}).call(this);
