// Generated by CoffeeScript 1.3.3
(function() {
  var UniversityController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  UniversityController = (function(_super) {

    __extends(UniversityController, _super);

    function UniversityController() {
      this.renderAll = __bind(this.renderAll, this);
      UniversityController.__super__.constructor.call(this, '.universities', window.App.University);
    }

    UniversityController.prototype.renderAll = function() {
      var compiled, header, key, model;
      compiled = (function() {
        var _ref, _results;
        _ref = this.models;
        _results = [];
        for (key in _ref) {
          model = _ref[key];
          _results.push(this.listTemplate(model));
        }
        return _results;
      }).call(this);
      this.el.html(compiled.join(" "));
      header = "<section class=\"normal\">\n  <h1><strong>PedU</strong></h1>\n</section>";
      this.el.prepend(header);
      return this.startList(this.models);
    };

    UniversityController.prototype.listTemplate = function(model) {
      model.area_of_service = model.area_of_service || 'Not available';
      return "<section class=\"school normal\">\n  <div class=\"image\">\n    <figure>\n      <img src=\"" + (model.image_url || '//placehold.it/128.png') + "\" />\n    </figure>\n  </div>\n\n  <div class=\"content\">\n    <header>\n      <div class=\"name\">" + model.name + "</div class=\"name\">\n    </header>\n    <h4>Definition of Service</h4>\n    <p>" + model.definition_of_service + "</p>\n\n    <h4>Area of Service</h4>\n    <p>" + model.area_of_service + "</p>\n  </div>\n</section>";
    };

    UniversityController.prototype.itemTemplate = function(model) {};

    return UniversityController;

  })(window.App.Controller);

  window.App.UniversityController = UniversityController;

}).call(this);
