// Generated by CoffeeScript 1.3.3
(function() {
  var WordpressFeed,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  google.load('feeds', 1);

  WordpressFeed = (function(_super) {

    __extends(WordpressFeed, _super);

    WordpressFeed.base_url = "https://pangeaeducation.wordpress.com/category/";

    WordpressFeed.feeds = {};

    WordpressFeed.fetch = function(number, feed) {
      if (number == null) {
        number = 10;
      }
      if (feed == null) {
        feed = "blog";
      }
      WordpressFeed.feeds[feed] = new google.feeds.Feed("" + WordpressFeed.base_url + feed + "/feed/");
      WordpressFeed.feeds[feed].setNumEntries(number);
      return WordpressFeed.feeds[feed].load(function(results) {
        var entry, feedEntries, _i, _len, _ref;
        if (!results.error) {
          feedEntries = new Array;
          _ref = results.feed.entries;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            entry = _ref[_i];
            feedEntries.push(new WordpressFeed(entry));
          }
          return WordpressFeed.trigger("feed-loaded:" + feed, feedEntries);
        }
      });
    };

    function WordpressFeed(entry) {
      var _ref;
      console.log(entry);
      this.title = entry.title;
      this.url = entry.link;
      this.description = entry.contentSnippet;
      this.content = entry.content;
      this.date = new Date(entry.publishedDate);
      this.linkText = "Learn More";
      this.image = ((_ref = entry.mediaGroups[0].contents[1]) != null ? _ref.url.split('?')[0] : void 0) + "?w=1000" || "http://placehold.it/1000x400";
    }

    return WordpressFeed;

  }).call(this, window.App.Events);

  window.App.WordpressFeed = WordpressFeed;

}).call(this);
