// Generated by CoffeeScript 1.3.3
(function() {
  var Wordpress,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Wordpress = (function(_super) {

    __extends(Wordpress, _super);

    function Wordpress(opts) {
      Wordpress.__super__.constructor.call(this, opts);
      this.el = opts.element;
      opts.lat || (opts.lat = 1.37);
      opts.lng || (opts.lng = 32.29);
      this.defaultZoom = opts.zoom || 13;
      this.styleUrl = opts.styleUrl || "http://{s}.tile.cloudmade.com/703a104d15d44e2885f6cedeaaec6d30/78177/256/{z}/{x}/{y}.png";
      this.center = new L.LatLng(opts.lat, opts.lng);
      this.setupMap();
    }

    Wordpress.prototype.setupMap = function() {
      this.map = L.map(this.el, {
        zoom: 13
      });
      this.map.setView(this.center, this.defaultZoom);
      this.mainTileLayer = L.tileLayer(this.styleUrl);
      return this.mainTileLayer.addTo(this.map);
    };

    return Wordpress;

  })(window.App.Model);

  window.App.Wordpress = Wordpress;

}).call(this);
