// Generated by CoffeeScript 1.3.3
(function() {

  window.App = {};

  $(function() {
    var boardContoller, el, imageCarousel, powerfulController, schoolController, teamController, universityController, _i, _len, _ref, _results;
    if (location.pathname === '/schools.html') {
      schoolController = new App.SchoolController();
      universityController = new App.UniversityController();
    } else if (location.pathname === '/' || location.pathname === '/index.html') {
      imageCarousel = new App.CarouselController();
    } else if (location.pathname === '/about.html') {
      boardContoller = new App.PeopleController('board');
      teamController = new App.PeopleController('team');
    } else if (location.pathname === '/programs.html') {
      powerfulController = new App.PowerfulController();
    }
    _ref = $('.countdown');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      el = _ref[_i];
      _results.push(new App.Countdown({
        el: el,
        target: new Date(2013, 0, 15)
      }));
    }
    return _results;
  });

}).call(this);
