// Generated by CoffeeScript 1.3.3
(function() {

  window.App = {};

  $(function() {
    var map;
    console.log(L);
    return map = new window.App.Map({
      element: 'map'
    });
  });

}).call(this);
