// Generated by CoffeeScript 1.3.3
(function() {

  window.App = {};

  $(function() {
    var map;
    map = new window.App.Map({
      element: 'map'
    });
    return window.App.MarkFudge.fudge();
  });

}).call(this);
