// Generated by CoffeeScript 1.4.0
(function() {
  var Timeline;

  Timeline = (function() {

    Timeline.prototype.base_image = 'url';

    Timeline.prototype.stage_urls = [];

    function Timeline(school, el, width) {
      Timeline.__super__.constructor.apply(this, arguments);
      this.school = school;
      this.el = $(el);
      this.width = 1000;
      this.startTime = moment(school.events[0].date);
      this.endTime = moment(school.events[school.events.length - 1].date);
      this.totalDays = moment(this.startTime).diff(this.endTime, 'days');
    }

    Timeline.prototype.convertX = function(event) {
      this.days = moment(this.startTime).diff(event.time, 'days');
      return (this.days / this.totalDays) * this.width;
    };

    Timeline.prototype.render = function() {
      var content, event, markers;
      markers = (function() {
        var _i, _len, _ref, _results;
        _ref = this.school.events;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          event = _ref[_i];
          _results.push(renderEvent(event));
        }
        return _results;
      }).call(this);
      return content = "<div style='" + this.width + "px' class='timeline'>\n    <ul class='inner'> \n        <li class='marker stage0'> </li>\n      " + (markers.join(" ")) + "\n    </ul>\n</div>";
    };

    Timeline.prototype.renderEvent = function(event) {
      var stage, xPoint;
      xPoint = convertX(event);
      stage = event.stage;
      return "<li class='marker stage" + stage + "' style='left:" + xPoint + "px'>date: \"2012-11-17T17:17:31Z\"\nstage: 1\ntext: \"this is some text\"</li>";
    };

    return Timeline;

  })();

  window.App.Timeline = Timeline;

}).call(this);
